apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::590184119069:role/eksctl-expense-1-nodegroup-nani-NodeInstanceRole-fslBYhsdrXeJ
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::590184119069:user/suresh
      username: suresh
    - groups:
      - expense-admin
      userarn: arn:aws:iam::315069654700:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-09T04:46:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1916"
  uid: 276091dc-84f9-4d0b-b6d6-7ae219b61a22
